# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 10080
cpus_per_task: 8
mem_gb: 4
name: ${hydra.job.override_dirname}
partition: x-men
# _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
